CREATE IF NOT EXISTS WAREHOUSE email_wh;
CREATE IF NOT EXISTS DATABASE email_db;
CREATE SCHEMA email_db.RAW;


CREATE OR REPLACE TABLE GMAIL_DATA (
    MESSAGE_ID                  VARCHAR(64),
    THREAD_ID                   VARCHAR(64),
    GMAIL_THREAD_ID             VARCHAR(64),    
    SENDER_RAW                  VARCHAR(512),
    SENDER_EMAIL                VARCHAR(256),
    SENDER_DISPLAY_NAME         VARCHAR(256),
    SENDER_DOMAIN               VARCHAR(256),
    SENDER_DOMAIN_TYPE          VARCHAR(64),    
    TO_EMAIL                    VARCHAR(1024),
    CC                          VARCHAR(1024),
    RECIPIENT_COUNT             NUMBER(5,0),    
    SUBJECT                     VARCHAR(1024),    
    FULL_DATE                   VARCHAR(1024),
    YEAR                        NUMBER(4,0),
    QUARTER                     NUMBER(1,0),
    MONTH                       NUMBER(2,0),
    MONTH_NAME                  NUMBER(2,0),
    WEEK                        NUMBER(2,0),
    DAY_OF_WEEK                 VARCHAR(16),
    DAY_NAME                    VARCHAR(16),
    IS_WEEKEND                  BOOLEAN,    
    FULL_TIME                   TIME,
    HOUR                        NUMBER(2,0),
    MINUTE                      NUMBER(2,0),
    AM_PM                       VARCHAR(2),
    TIME_BUCKET                 VARCHAR(32),    
    FOLDER                      VARCHAR(64),
    ALL_LABELS                  VARCHAR(512),    
    SIZE_BYTES                  NUMBER(12,0),
    ATTACHMENT_COUNT            NUMBER(5,0),
    HAS_ATTACHMENTS             BOOLEAN,
    REPLY_LATENCY_SEC           VARCHAR(1024),    
    IS_READ                     BOOLEAN,
    IS_STARRED                  BOOLEAN,
    IS_REPLIED                  BOOLEAN,
    IS_FORWARDED                BOOLEAN,    
    THREAD_SUBJECT              VARCHAR(1024),
    THREAD_MESSAGE_COUNT        NUMBER(6,0),
    THREAD_FIRST_MESSAGE_AT     VARCHAR(1024),
    THREAD_LAST_MESSAGE_AT      VARCHAR(1024),
    THREAD_DURATION_SEC         NUMBER(12,0),
    THREAD_PARTICIPANT_COUNT    NUMBER(5,0)
);